### ISSUE TITLE
Step 2 Error: recognize takes from 1 to 2 positional arguments 

### ISSUE THREAD

**Issue by CaptInfinity** [NatGr/annotate_audio#1]
attempting to execute step 2 after configuring gcp, enabling API and billing and installing dependencies listed, get_gcp_transcription.py 

Command:
`python get_gcp_transcription.py --audio_folder audio --csv sentences.csv --language_code en-US`

Error:

`files transcribed:   0%|                                                                                                                                   | 0/42 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "get_gcp_transcription.py", line 31, in <module>
    response = client.recognize(config, audio)
TypeError: recognize() takes from 1 to 2 positional arguments but 3 were given`

**Comment by NatGr** [comment]
Hello,
I was using google-cloud-speech version 1.3.2, it appears they are at version 2.10 now and they made some breaking changes https://googleapis.dev/python/speech/latest/UPGRADING.html.

If you are using v2, could you please try replacing 

`response = client.recognize(config, audio)`
(line 31)
by 
`request = speech_v1.RecognizeRequest(request={"config": config, "audio": audio})
response = client.list_voices(request=request)`

you might also need to replace speech_v1 by speech in the file, (latest versions of the doc don't refer to speech_v1 anymore but you got an error at line 31 so perhaps it still works).

I lost the audio files I used with that project so I would appreciate to know if doing so worked for you so I can update the repo afterwards.

**Comment by CaptInfinity** [comment]
Good news is that pip install google-cloud-speech==1.3.2 still works and the package runs great!! I was able to produce annotated results and review them with step 3. Love it!!

Bad news, I attempted to the google migration guidance and still have an issue:
`Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf3/lib/python3.6/site-packages/proto/message.py", line 505, in __init__
    pb_type = self._meta.fields[key].pb_type
KeyError: 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_gcp_transcription.py", line 31, in <module>
    request = speech.RecognizeRequest(request={"config": config, "audio": audio})
  File "/opt/anaconda3/envs/tf3/lib/python3.6/site-packages/proto/message.py", line 511, in __init__
    "Unknown field for {}: {}".format(self.__class__.__name__, key)
ValueError: Unknown field for RecognizeRequest: request`

**Comment by NatGr** [comment]
I'm glad it works!

maybe config should be a specific object and not a json anymore with version 2.10
https://googleapis.dev/python/speech/latest/speech_v1/types.html#google.cloud.speech_v1.types.RecognitionConfig

I'll try to find a sample and make it work with version 2.10 tomorrow

**Comment by NatGr** [comment]
just updated the repo, this should work with version 2.X as well now

**Comment by CaptInfinity** [comment]
Worked perfectly! Only 2 nit-picks on your merge:

1. the requirements.txt file is now 'requirement.txt' and needs to be updated in Readme
2. the link on configuring the google auth should probably be this link:https://cloud.google.com/docs/authentication/getting-started

Looks great! thanks so much for merging in the change to support the latest google API! you rock!

**Comment by NatGr** [comment]
Indeed you are right, I'll update that.
Thanks for the feedback and kind words ^^
